<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <title>Facturacion | Multi Empresa</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description">
    <meta content="Themesbrand" name="author">
    <!-- App favicon -->
    <link rel="shortcut icon" href="<?=URL::to('public/assets/images/favicon.ico')?>">

    <!-- Bootstrap Css -->
    <link href="<?=URL::to('public/assets/css/bootstrap.min.css')?>" id="bootstrap-style" rel="stylesheet" type="text/css">
    <!-- Icons Css -->
    <link href="<?=URL::to('public/assets/css/icons.min.css')?>" rel="stylesheet" type="text/css">
    <!-- App Css-->
    <link href="<?=URL::to('public/assets/css/app.min.css')?>" id="app-style" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="<?=URL::to('public/plugin/sweetalert2/sweetalert2.min.css')?>">
    <script>
        const _URL='<?=URL::base()?>';
    </script>
    <style>
        a{
            color:#02a499
        }
    </style>

    <style>
        @keyframes ldio-407auvblvok {
            0% { transform: rotate(0) }
            100% { transform: rotate(360deg) }
        }
        .ldio-407auvblvok div { box-sizing: border-box!important }
        .ldio-407auvblvok > div {
            position: absolute;
            width: 79.92px;
            height: 79.92px;
            top: 15.540000000000001px;
            left: 15.540000000000001px;
            border-radius: 50%;
            border: 8.88px solid #000;
            border-color: #626ed4 transparent #626ed4 transparent;
            animation: ldio-407auvblvok 1s linear infinite;
        }

        .ldio-407auvblvok > div:nth-child(2), .ldio-407auvblvok > div:nth-child(4) {
            width: 59.940000000000005px;
            height: 59.940000000000005px;
            top: 25.53px;
            left: 25.53px;
            animation: ldio-407auvblvok 1s linear infinite reverse;
        }
        .ldio-407auvblvok > div:nth-child(2) {
            border-color: transparent #02a499 transparent #02a499
        }
        .ldio-407auvblvok > div:nth-child(3) { border-color: transparent }
        .ldio-407auvblvok > div:nth-child(3) div {
            position: absolute;
            width: 100%;
            height: 100%;
            transform: rotate(45deg);
        }
        .ldio-407auvblvok > div:nth-child(3) div:before, .ldio-407auvblvok > div:nth-child(3) div:after {
            content: "";
            display: block;
            position: absolute;
            width: 8.88px;
            height: 8.88px;
            top: -8.88px;
            left: 26.64px;
            background: #626ed4;
            border-radius: 50%;
            box-shadow: 0 71.04px 0 0 #626ed4;
        }
        .ldio-407auvblvok > div:nth-child(3) div:after {
            left: -8.88px;
            top: 26.64px;
            box-shadow: 71.04px 0 0 0 #626ed4;
        }

        .ldio-407auvblvok > div:nth-child(4) { border-color: transparent; }
        .ldio-407auvblvok > div:nth-child(4) div {
            position: absolute;
            width: 100%;
            height: 100%;
            transform: rotate(45deg);
        }
        .ldio-407auvblvok > div:nth-child(4) div:before, .ldio-407auvblvok > div:nth-child(4) div:after {
            content: "";
            display: block;
            position: absolute;
            width: 8.88px;
            height: 8.88px;
            top: -8.88px;
            left: 16.650000000000002px;
            background: #02a499;
            border-radius: 50%;
            box-shadow: 0 51.06px 0 0 #02a499;
        }
        .ldio-407auvblvok > div:nth-child(4) div:after {
            left: -8.88px;
            top: 16.650000000000002px;
            box-shadow: 51.06px 0 0 0 #02a499;
        }
        .loadingio-spinner-double-ring-8kmkrab6ncg {
            width: 111px;
            height: 111px;
            display: inline-block;
            overflow: hidden;
            background: rgba(255, 255, 255, 0);
        }
        .ldio-407auvblvok {
            width: 100%;
            height: 100%;
            position: relative;
            transform: translateZ(0) scale(1);
            backface-visibility: hidden;
            transform-origin: 0 0; /* see note above */
        }
        .ldio-407auvblvok div { box-sizing: content-box; }
        /* generated by https://loading.io/ */
    </style>
    <style>

        #loader-menor{
            position: fixed;
            top: 0;
            left: 0;
            z-index: 9999;
            width: 100%;
            height: 100%;
            display: none;
            background-color: #ffffff96;
            line-height: 100vh;
            text-align: center;
        }
        #loader-init{
            position: fixed;
            top: 0;
            left: 0;
            z-index: 9999;
            width: 100%;
            height: 100%;
            background-color: #ffffff;
            line-height: 100vh;
            text-align: center;
        }
    </style>

</head>

<body class="account-pages">
<div  id="loader-init">
    <div class="loadingio-spinner-double-ring-8kmkrab6ncg">
        <div class="ldio-407auvblvok">
            <div></div>
            <div></div>
            <div><div></div></div>
            <div><div></div></div>
        </div>
    </div>
</div>
<div style="display: none" id="loader-menor">
    <div class="loadingio-spinner-double-ring-8kmkrab6ncg">
        <div class="ldio-407auvblvok">
            <div></div>
            <div></div>
            <div><div></div></div>
            <div><div></div></div>
        </div>
    </div>
</div>
<!-- Begin page -->
<div class="accountbg" style="background: url('<?=URL::to('public/assets/images/lbt.jpg')?>');background-size: cover;background-position: center;"></div>

<div class="wrapper-page account-page-full"  style="background: black">

    <div class="card shadow-none" style="background: black">
        <div class="card-block">

            <div class="account-box">

                <div class="card-box shadow-none p-4">
                    <div class="p-2" style="color: white">
                        <div class="text-center mt-4">
                            <a href="javascript:void(0)"><img style="max-width: 100%;" src="<?=URL::to('public/img/logo.png')?>" alt="logo"></a>
                        </div>

                        <h4 class="font-size-18 mt-5 text-center">Bienvenido de nuevo !</h4>
                        <p class="text-muted text-center">Inicie sesión para continuar </p>
                        <h4 class="font-size-18  text-center">Facturacion Electronica</h4>
                        <form class="mt-4">

                            <div class="mb-3">
                                <label class="form-label" for="username">Usuario, Email</label>
                                <input required name="user" type="text" class="form-control" id="username" placeholder="">
                            </div>


                            <div class="mb-3">
                                <label class="form-label" for="userpassword">Contraseña</label>
                                <input required name="clave" type="password" class="form-control" id="userpassword" placeholder="">
                            </div>

                            <div class="mb-3 row">
                                <div class="col-sm-6">
                                    <div class="form-check">
                                        <input type="checkbox" class="form-check-input" id="customControlInline">
                                        <label class="form-check-label" for="customControlInline">Recordarme</label>
                                    </div>
                                </div>
                                <div class="col-sm-6 text-end">
                                    <button class="btn btn-success w-md waves-effect waves-light" type="submit">Ingresar</button>
                                </div>
                            </div>

                            <div class="mb-3 mt-2 mb-0 row">
                                <div class="col-12 mt-3">
                                    <a href="pages-recoverpw-2.html"><i class="mdi mdi-lock"></i> ¿Olvidastes tu contraseña?</a>
                                </div>
                            </div>

                        </form>

                        <div class="mt-5 pt-4 text-center">
                            <p hidden>Regístrate ? <a href="pages-register-2.html" class="fw-medium text-primary"> Signup now </a> </p>
                            <p>© <script>document.write(new Date().getFullYear())</script> <b>HATUNA desarrollado junto a <br> <a href="https://magustechnologies.com/" target="_blank">Magus Technologies</a></b></p><p> Todos los derechos reservados</p>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>

</div>



<!-- JAVASCRIPT -->
<script src="<?=URL::to('public/assets/libs/jquery/jquery.min.js')?>"></script>
<script src="<?=URL::to('public/assets/libs/bootstrap/js/bootstrap.bundle.min.js')?>"></script>
<script src="<?=URL::to('public/assets/libs/metismenu/metisMenu.min.js')?>"></script>
<script src="<?=URL::to('public/assets/libs/simplebar/simplebar.min.js')?>"></script>
<script src="<?=URL::to('public/assets/libs/node-waves/waves.min.js')?>"></script>
<script src="<?=URL::to('public/assets/js/app.js')?>"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>

</body>
<script>
    (function verificador() {
        if (localStorage.getItem("_token")){
            $.ajax({
                url: _URL+"/ajs/verificador/token",
                type: "POST",
                data: {
                    token:localStorage.getItem("_token"),
                    s:false
                },
                success(resp){
                    console.log(resp);
                    resp=JSON.parse(resp);
                    if (resp.res){
                        $("#loader-init").hide();
                        location.href=_URL
                    }else{
                        localStorage.removeItem("_token")
                        $("#loader-init").hide();
                    }
                }
            })
        }else{
            $("#loader-init").hide();
        }
    })()

    $(document).ready(function(){

        $("form").submit(function (evt){
            evt.preventDefault();
            $("#loader-menor").show();
            $.ajax({
                type: "POST",
                url: _URL+"/login",
                data:  $("form").serialize(),
                success: function (resp) {
                    $("#loader-menor").hide();
                    //console.log(resp);
                    resp=JSON.parse(resp);
                    console.log(resp);
                    if (resp.res){
                        localStorage.setItem("_token",resp.token)
                        location.href=_URL
                    }else{

                        Swal.fire({icon: 'warning',
                            title: resp.msg})
                    }
                },
                error(){
                    $("#loader-menor").hide();
                }
            });
        });
    })
</script>

</html>